# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTEzYTQ3MTIwZmM5NmE4MjQ5ZmRkYzMyN2NkZWI0ZTM5ODAwYTBhYjcxOGQyNWE4MzkwNTQxZjc1ZDFhYWM0MzI0YmMwMWI2MDVmYTMzNTE5MTVhNTVjMmZhYTI4NDFhN2IyY2NiMjAxMTUzMjVkNGNjNGM2YTcxOWFhMTUxMGE=
