package pl.edu.bikerental.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BikeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBikeAllPropertiesEquals(Bike expected, Bike actual) {
        assertBikeAutoGeneratedPropertiesEquals(expected, actual);
        assertBikeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBikeAllUpdatablePropertiesEquals(Bike expected, Bike actual) {
        assertBikeUpdatableFieldsEquals(expected, actual);
        assertBikeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBikeAutoGeneratedPropertiesEquals(Bike expected, Bike actual) {
        assertThat(actual)
            .as("Verify Bike auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBikeUpdatableFieldsEquals(Bike expected, Bike actual) {
        assertThat(actual)
            .as("Verify Bike relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSerialNumber()).as("check serialNumber").isEqualTo(expected.getSerialNumber()))
            .satisfies(a -> assertThat(a.getBikeType()).as("check bikeType").isEqualTo(expected.getBikeType()))
            .satisfies(a -> assertThat(a.getPricePerHour()).as("check pricePerHour").isEqualTo(expected.getPricePerHour()))
            .satisfies(a -> assertThat(a.getAvailable()).as("check available").isEqualTo(expected.getAvailable()))
            .satisfies(a -> assertThat(a.getProductionDate()).as("check productionDate").isEqualTo(expected.getProductionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBikeUpdatableRelationshipsEquals(Bike expected, Bike actual) {
        assertThat(actual)
            .as("Verify Bike relationships")
            .satisfies(a -> assertThat(a.getCategorieses()).as("check categorieses").isEqualTo(expected.getCategorieses()));
    }
}
