package pl.edu.bikerental.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerProfileAllPropertiesEquals(CustomerProfile expected, CustomerProfile actual) {
        assertCustomerProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerProfileAllUpdatablePropertiesEquals(CustomerProfile expected, CustomerProfile actual) {
        assertCustomerProfileUpdatableFieldsEquals(expected, actual);
        assertCustomerProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerProfileAutoGeneratedPropertiesEquals(CustomerProfile expected, CustomerProfile actual) {
        assertThat(actual)
            .as("Verify CustomerProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerProfileUpdatableFieldsEquals(CustomerProfile expected, CustomerProfile actual) {
        assertThat(actual)
            .as("Verify CustomerProfile relevant properties")
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getLoyaltyPoints()).as("check loyaltyPoints").isEqualTo(expected.getLoyaltyPoints()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerProfileUpdatableRelationshipsEquals(CustomerProfile expected, CustomerProfile actual) {
        assertThat(actual)
            .as("Verify CustomerProfile relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
